[package]
name = "event"
version = "0.5.0"
authors = ["Matthew Kozachek <mkozachek@gmail.com>"]
repository = "https://github.com/mkozachek/Rust-Events"
keywords = ["Events", "events", "event driven", "event design", "event pattern"]

[lib]
name = "event"
path = "src/lib.rs"
crate-type = ["dylib"]

